

name: WFD-Create Schedule
 
on:

  workflow_dispatch:

    inputs:

      guid:

        description: Unique Identifier [optional] :(Unique String to identify the Workflow e.g. test_snapshot)

        type: string

      PROJECT_NAME:

        description: Environment

        required: true

        type: choice

        options: [dev, int, prd, cfn]

      ENVIRONMENTS_LIST:

        description: Comma separated list of stack environments. e.g. kacd01_sup01,kacd01_pip15

        required: true

        type: string

      Release_Date_Time:

        description: 'Scheduled Release Date and Time (UTC) - YYYY-MM-DD HH:MM'

        required: true

        default: '' # User must provide this

      PLAN_FOLDER:

        description: PLAN_FOLDER. e.g. 23 to 29 june

        type: string

        required: true

      WORKFLOW_TAG:

        description: 'Workflow Tag (e.g., timeschedule etc)'

        required: true

        type: string  

      PHASE:

        description: Phase e.g. pre-maintenance, maintenance, post-maintenance

        type: choice

        options: [express-upgrade, pre-maintenance, maintenance, post-maintenance]

        required: true

      UPGRADE_LIVE_ONLY:

        description: Tick to upgrade only live deployments, else will attempt to upgrade all the deployments.

        type: boolean

        required: true

        default: false
 
permissions:

  contents: write
 
jobs:
 
  Creating-Schedule:

    steps:
 
      - name: Checkout repo

        uses: actions/checkout@v4

      - name: Generate workflows For Plan

        run: |

          python scripts/wfm_orchestration/generate_gha_workflows1.py \

            --plans-dir "Plans/${{ inputs.PLAN_FOLDER }}" \

            --workflow-tag "${{ inputs.WORKFLOW_TAG }}" \

            --releaseDateTime "${{ inputs.Release_Date_Time }}" \

            --environments "${{ inputs.ENVIRONMENTS_LIST }}"

      - name: Run commit scriptAdd commentMore actions

        env:

          ORCH_APP_PRIVATE_KEY_B64: ${{ secrets.ORCH_APP_PRIVATE_KEY_B64 }}

        run: |

          python scripts/wfm_orchestration/commit_with_github_app1.py

 
  Validating-Plan:

    needs: Creating-Schedule

    steps:

      - name: Validate Plan Format

        run: |

          echo "Validating the plan format..."

          echo "Plan is valid."

 
